server:
  port: 8200


# Datasource configuration

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:notes_db}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  cloud:
    openfeign:
      circuitbreaker:
        alphanumeric-ids:
          enabled: true


resilience4j:
  circuitbreaker:
    instances:
      notesClient:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowType: COUNT_BASED
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    instances:
      notesClient:
        maxAttempts: 3
        waitDuration: 500
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
  timeLimiter:
    instances:
      notesClient:
        timeoutDuration: 2s

#management:
#  health:
#    circuitbreakers:
#      enabled: true
#  endpoint:
#    health:
#      show-details: always