
spring:
  cloud:
    gateway:
        routes:
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/api/users/**

          - id: notes-service
            uri:
                lb://notes-service
            predicates:
                - Path=/api/notes/**
eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/
